Models/ErrorViewModel.cs
using System;

namespace Practica04.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FormularioIngreso.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Practica04.Models
{
    public class FormularioIngreso
    {
         public int Id{get;set;}
         [Required]

         public string NombreUsuario{get;set;}
        
          public ICollection<FormularioRegistro> FormularioRegistros{get;set;}
    }
}
// gg;

Models/FormularioRegistro.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Practica04.Models
{
    public class FormularioRegistro
    {
         public int Id{get;set;}
        
[Required]
          public string titulofoto{get;set;}
           [Required]
         public string urlfoto{get;set;}
  [Required]
          public string comentario{get;set;}
        
[Required]
          public string subidopor{get;set;}
          public DateTime FechaRegistro{get;set; }
         public FormularioIngreso FormularioIngreso{get;set;}
           public int FormularioIngresoId {get;set;}
            
          public FormularioRegistro(){
                FechaRegistro = DateTime.Now;
                }

    }
      
    }
    // gg;

Models/RegistroContext.cs
using Microsoft.EntityFrameworkCore;

namespace Practica04.Models
{
    public class RegistroContext : DbContext
    {
        
        
         public DbSet<FormularioRegistro> FormularioRegistros{get;set; }

         public DbSet<FormularioIngreso> FormularioIngresos{get;set; }



          public RegistroContext(DbContextOptions dco) : base(dco){

          }
          }
}
// gg;

Controllers/CuentaController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Practica04.Models;
using Microsoft.AspNetCore.Mvc;
namespace  Practica04.Controllers
{
    public class CuentaController : Controller
    {
        private readonly SignInManager<IdentityUser> _sim;
        private readonly UserManager<IdentityUser> _um;
        public CuentaController(
            SignInManager<IdentityUser> sim,
            UserManager<IdentityUser> um) {
                _sim = sim;
                _um = um;
// gg;
      }

        public IActionResult IniciarSesion() {
            return View();
        }

        [HttpPost]
        public IActionResult IniciarSesion(string usuario, string password) {
            var result = _sim.PasswordSignInAsync(usuario, password, false, false).Result;
            if (result.Succeeded) {
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Los datos son incorrectos");
            return View();
        }

        public async Task<IActionResult> CerrarSesion() {
            await _sim.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult CrearCuenta() {
            return View();
        }

        [HttpPost]
        public IActionResult CrearCuenta(string email, string password) {
            var usuario = new IdentityUser(email);
           
            var resultado = _um.CreateAsync(usuario, password).Result;

            if (resultado.Succeeded) {
                return RedirectToAction("Index", "Home");
            }
            
            foreach (var error in resultado.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Practica04.Models;
namespace Practica04.Controllers
{
    public class HomeController : Controller
    {
       private readonly RegistroContext _context;

     public HomeController(RegistroContext context)
     {
         _context = context;
     }

        public IActionResult Index()
        {
            var formularioRegistros = _context.FormularioRegistros.Include(x => x.FormularioIngreso).Where(x => x.FechaRegistro.AddDays(5) >= DateTime.Now).ToList();
            return View(formularioRegistros);
        }
// gg;
     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/RegistroController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Practica04.Models;

namespace Practica04.Controllers
{
     
    public class RegistroController : Controller
    {
 
     private readonly RegistroContext _context;

     public RegistroController(RegistroContext context)
     {
         _context = context;
     }
   
       public IActionResult Registros()
        {
             ViewBag.FormularioIngresos= _context.FormularioIngresos.Select(x => new SelectListItem(x.NombreUsuario,x.Id.ToString()));
            return View();
        }


        [HttpPost]


public IActionResult Registros(FormularioRegistro p) {
    if(ModelState.IsValid){
    _context.FormularioRegistros.Add(p);
     _context.SaveChanges();
     return RedirectToAction("Index","Home");
    }else {
        return View(p);
    }
    }
    }
}
// gg;

Views/Cuenta/CrearCuenta.cshtml
<h1>Crear cuenta de usuario</h1>


<form method="post">

    <div asp-validation-summary="All"></div>

    <div class="form-group">
        <label>Correo:</label>
        <input type="email" name="email" class="form-control" />
    </div>
    <div class="form-group">
        <label>Contraseña:</label>
        <input type="password" name="password" class="form-control" />
    </div>
    <button class="btn btn-primary">Crear cuenta de usuario</button>
</form>

Views/Cuenta/IniciarSesion.cshtml
<h1>Iniciar sesión</h1>


<form method="post">

    <div asp-validation-summary="All"></div>

    <div class="form-group">
        <label>Usuario:</label>
        <input type="email" name="usuario" class="form-control" />
    </div>
    <div class="form-group">
        <label>Contraseña:</label>
        <input type="password" name="password" class="form-control" />
    </div>
    <button class="btn btn-primary">Iniciar sesión</button>
</form>

Views/Home/Index.cshtml
@model List<FormularioRegistro>
@{
    ViewData["Title"] = "PERU FAILS";
}

@if (Model.Count() == 0){
    
     <p class="text-center">Peru Fails </p>
    <p class="text-center">No se ingreso fotos</p>
} else {
    <div class="row">
    @foreach(var Registros in Model)
    {
<div class="col-4 text-center">
  <p>Titulo:</p><h2>@Registros.titulofoto</h2>
 <p>Subidopor:</p><p>@Registros.subidopor</p>
 <img src="@Registros.urlfoto" class="img-fluid"/>
 <p>Enviar comentarios:</p> <p>@Registros.comentario</p>
 <button class="btn btn-primary">Enviar Comentario</button>

</div>
    }
    </div>
}

Views/Registro/Registros.cshtml
@model FormularioRegistro
<h1>REGISTRAR A Usuario</h1>

<div asp-validation-summary="All"></div>

<form method="post">
<div class="form-group">
<label asp-for="titulofoto"></label>
<input asp-for="titulofoto" class="form-control"/>
</div>
<div class="form-group">
<label asp-for="urlfoto"></label>
<input asp-for="urlfoto" class="form-control"/>
</div>

<div class="form-group">
<label asp-for="comentario"></label>
<textarea  asp-for="comentario" class="form-control"></textarea>
</div>
<div class="form-group">
<label asp-for="subidopor"></label>
<input asp-for="subidopor" class="form-control"/>
</div>
<div class="form-group">
<label asp-for="FormularioIngreso"></label>
<input asp-for="FormularioIngresoId" asp-items="ViewBag.FormularioIngresos"class="form-control"></select>
</div>
<button class="btn btn-primary">REGISTRAR</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
              <img src="https://th.bing.com/th/id/OIP.oacIcIh0u2uLTVdZqpaUMwHaEK?pid=ImgDet&rs=1"width="300"/>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica04</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registro" asp-action="Registros">Subir fail</a>
                        </li>
                          @if (!User.Identity.IsAuthenticated) {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="CrearCuenta">Crear cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="IniciarSesion">Iniciar Sesión</a>
                        </li>
                        } else {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="CerrarSesion">Cerrar Sesión</a>
                        </li>
                           }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Practica04 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>